### ISSUE TITLE
Fix image responsiveness 

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratumprotocol.org#146]
Best example of non-responsive image can be seen here https://deploy-preview-142--startling-capybara-2231ea.netlify.app/getting-started.html

**Comment by Abhijay007** [comment]
@pavlenex I want to work on this issue, can you please assign this to me?

**Comment by pavlenex** [comment]
Sure @Abhijay007 , do you have a time-frame in mind? Bear in mind you'd have to work on top of my PR #142 where image responsiveness issue is visible.

**Comment by Abhijay007** [comment]
> Sure @Abhijay007 , do you have a time-frame in mind? Bear in mind you'd have to work on top of my PR #142 where image responsiveness issue is visible.

@pavlenex I will start working on it, I am in the process of figuring out how I can resolve this, this might not take much time, and the other thing is you said I need to work on the top of this PR  #142, so do I wait for it to get merge of just fork the change of that pr and start working on the same ?

**Comment by pavlenex** [comment]
@Abhijay007 I think since that PR is still waiting for some formatting updates, best is to work on top of it, but if you find that the underlaying issue can be fixed otherwise, feel free to work on `master` and then we can merge your PR first, whatever works for you, I was just able to identify the problem once I added an svg in #142.

**Comment by Abhijay007** [comment]
> @Abhijay007 I think since that PR is still waiting for some formatting updates, best is to work on top of it, but if you find that the underlying issue can be fixed otherwise, feel free to work on `master` and then we can merge your PR first, whatever works for you, I was just able to identify the problem once I added an SVG in #142.

Okay, thanks for clearing this @pavlenex, I will start working on the `master`, and if any of the image responsiveness issues are left after that we will cover that in a new PR if that works.

**Comment by Abhijay007** [comment]
@pavlenex after searching around, I found two solutions for this issue

first: we can set a universal style for the image in the `index.styl`  file, as I did here : (attached image )

one problem with this is that it will give this property to all the images throughout the site, but I don't think that will be an issue because, in most of the images, we different the inline CSS to specific styles, so that might not cause any overwrite issues 

second: we can define the CSS for the specific images in the markdown file itself rather than the template. 

any thoughts on this ?

![image (3)](https://user-images.githubusercontent.com/64387054/221169265-e7064797-a87a-490e-b397-3cc7643d001a.png)

![image (4)](https://user-images.githubusercontent.com/64387054/221169280-c5ff1dd3-0e66-44ef-89b3-d3897670faa4.png)

also after assigning CSS to the image I re-checked the whole site and nothing changes for the images as most of the images are rendering there CSS from the template where we defined that inline.

**Comment by pavlenex** [comment]
@Abhijay007 Thanks for quickly tackling this one. If you double-checked that the proposed change doesn't influence other images on the site, I'd say we go with global settings, once you do a PR we will have a test preview via Netlify anyway, so we can double-check.

**Comment by Abhijay007** [comment]
> @Abhijay007 Thanks for quickly tackling this one. If you double-checked that the proposed change doesn't influence other images on the site, I'd say we go with global settings, once you do a PR we will have a test preview via Netlify anyway, so we can double-check.

sure will open a PR soon :)
